# Server Port
server.port=8761

# Application Name
spring.application.name=discovery-service

# Eureka Server Config
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Self Preservation (optional)
eureka.server.enable-self-preservation=false
# Actuator
management.endpoints.web.exposure.include=*

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
